# Transformações utilizando Pandas

Pandas é uma ferramenta robusta de tratamento e manipulação de dados. Parte do pacote [SciPy](https://www.scipy.org/), funciona como parte de um ecosistema rico em ferramentas para matemáticos e engenheiros.

Aqui apresentaremos alguns métodos simples de limpeza e formatação em um conjunto de dados real.

Vamos utilizar a base `md_bruto.csv`, baixada diretamente do site do governo através do [endereço disponível na sua plataforma de dados](https://dados.gov.br/dataset/serie-historica). Essa base descreve os gastos das unidades do Ministério da Defesa do ano 2000 até Junho de 2020.

Começaremos importando a biblioteca.

In [1]:
import pandas as pd

A primeira verificação é simples, podemos só ver o arquivo do jeito que ele está. Não é um arquivo grande, então conseguimos mostrar no console. Outra boa opção é abrir em um editor de texto.

In [2]:
with open("../datasets/md_bruto.csv", "r") as f:
    conteudo = f.read()
    print(conteudo.split("\n"))

['Unidade Orçamentária ;GRUPO DE DESPESA;2000;2001;2002;2003;2004;2005;2006;2007;2008;2009;2010;2011;2012;2013;2014;2015;2016;2017;2018;2019;Dotação atualizada 2020*;Empenhado', 'Total Ministério da Defesa;TOTAL;20.696,4;25.494,0;28.176,2;25.777,8;28.513,2;33.021,6;35.581,1;39.766,7;44.621,3;50.990,2;59.452,3;61.663,1;66.378,8;70.881,0;76.874,2;81.873,5;84.508,9;93.120,1;102.938,3;111.998,3;108.879,6;87.786,1', 'Total Ministério da Defesa;Pessoal e Encargos Sociais;15.119,8;18.724,1;21.332,9;21.111,5;22.612,4;24.856,8;28.522,1;30.734,0;35.328,6;39.403,1;43.648,9;46.449,1;47.270,9;51.261,8;55.591,8;61.566,2;64.356,8;70.740,1;76.018,8;81.102,9;84.718,8;74.853,1', 'Total Ministério da Defesa;Juros e Encargos da Dívida;322,4;390,1;632,1;460,7;411,2;1.318,6;338,0;178,3;56,5;330,6;103,8;226,3;234,7;318,9;386,8;402,3;335,3;373,0;469,0;497,0;828,2;316,0', 'Total Ministério da Defesa;Outras Despesas Correntes;2.493,5;2.983,5;2.665,2;2.793,8;3.520,4;4.214,0;4.197,3;4.735,1;5.533,5;6.282,5;7.304,2;8.088,5;8.206,7;9.376,8;11.196,8;10.676,6;11.448,1;12.019,7;13.079,7;13.976,9;14.302,1;7.222,7', 'Total Ministério da Defesa;Investimentos;1.716,3;1.947,8;1.686,4;878,8;1.549,1;1.917,5;1.757,7;2.669,1;3.406,7;4.798,4;8.241,3;6.529,5;10.033,7;8.956,7;8.258,2;7.239,9;6.949,1;8.518,4;9.104,9;7.878,5;7.131,6;4.514,5', 'Total Ministério da Defesa;Inversões Financeiras;0,1;20,5;2,0;12,4;1,8;2,8;51,2;609,2;81,0;4,0;3,5;3,6;18,7;5,7;97,7;301,6;129,8;258,8;2.890,0;7.162,8;80,0;13,3', 'Total Ministério da Defesa;Amortização da Dívida;1.044,2;1.428,1;1.857,5;520,7;418,3;711,9;714,9;841,1;215,0;171,5;150,6;366,1;614,1;961,0;1.342,9;1.686,9;1.289,8;1.210,1;1.375,9;1.380,2;1.818,8;866,4', 'Administração Direta;TOTAL;830,4;720,9;825,7;619,3;876,5;1.595,5;1.421,3;1.609,3;765,4;904,7;1.836,2;1.224,8;1.868,7;1.908,6;2.467,5;2.119,8;2.215,2;1.475,1;2.087,0;1.824,1;2.383,6;917,2', 'Administração Direta;Pessoal e Encargos Sociais;38,1;34,9;28,7;38,8;186,1;198,0;293,3;34,3;38,6;41,6;45,5;61,3;60,4;69,5;80,2;86,4;86,5;85,4;87,6;91,4;113,9;78,7', 'Administração Direta;Juros e Encargos da Dívida;29,6;42,0;234,4;349,1;335,7;290,1;240,8;101,3;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;;', 'Administração Direta;Outras Despesas Correntes;50,6;59,8;73,0;54,8;151,9;221,6;260,5;249,1;373,0;408,2;798,8;725,0;521,3;658,5;903,0;760,0;967,3;531,8;969,2;877,7;1.216,3;361,3', 'Administração Direta;Investimentos;600,3;383,7;329,3;124,9;152,2;646,4;216,4;366,5;275,8;455,0;991,8;438,5;1.287,1;1.180,6;1.390,1;977,1;1.043,6;819,1;1.030,1;855,0;1.053,3;477,2', 'Administração Direta;Inversões Financeiras;0,0;0,0;0,0;0,0;0,0;0,0;0,0;565,1;78,0;0,0;0,0;0,0;0,0;0,0;94,2;296,3;117,8;38,8;0,0;0,0;0,0;0,0', 'Administração Direta;Amortização da Dívida;111,8;200,5;160,4;51,6;50,6;239,5;410,3;293,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0', ' Comando da Aeronáutica;TOTAL;4.014,7;5.787,1;6.334,2;5.783,3;6.609,1;8.189,4;8.061,6;9.554,9;10.682,3;12.135,8;12.875,5;13.686,4;14.626,3;15.793,0;17.000,1;19.264,6;19.162,8;20.624,3;22.213,3;23.554,0;24.048,7;12.667,1', ' Comando da Aeronáutica;Pessoal e Encargos Sociais;3.177,0;4.031,5;4.554,8;4.636,5;4.951,0;5.402,1;6.342,6;6.957,0;8.034,9;8.960,6;9.931,6;10.798,5;10.886,7;11.834,3;12.900,3;14.239,6;14.841,3;16.267,3;17.464,2;18.606,8;19.415,7;9.720,2', ' Comando da Aeronáutica;Juros e Encargos da Dívida;65,0;116,4;273,5;67,5;42,5;1.004,5;80,2;66,7;51,0;274,0;54,7;122,3;95,7;134,8;168,6;188,3;166,8;208,7;275,6;312,6;513,6;206,2', ' Comando da Aeronáutica;Outras Despesas Correntes;508,8;672,1;585,8;587,3;724,4;818,4;775,3;1.095,3;1.168,0;1.164,1;1.231,8;1.391,0;1.480,9;1.657,7;1.783,1;1.565,9;1.590,9;1.284,5;1.609,7;1.642,2;1.482,0;648,8', ' Comando da Aeronáutica;Investimentos;125,1;780,1;622,9;339,5;760,8;665,7;658,0;951,2;1.249,4;1.582,3;1.509,7;1.176,8;1.902,5;1.794,6;1.633,5;2.662,7;2.168,8;2.462,2;2.339,2;2.425,0;1.954,6;1.709,1', ' Comando da Aeronáutica;Inversões Financeiras;;;;;;;;;;;;;;;;0,0;0,0;0,0;0,0;0,0;25,1;0,0', ' Comando da Aeronáutica;Amortização da Dívida;138,8;187,0;297,2;152,5;130,5;298,7;205,6;484,7;179,0;154,8;147,8;197,8;260,5;371,6;514,6;608,1;395,0;401,6;524,7;567,4;657,7;382,8', ' Comando do Exército;TOTAL;9.072,8;11.185,1;12.728,4;11.807,0;12.697,1;14.097,2;15.920,1;17.321,4;19.852,7;22.139,5;24.973,3;26.838,7;28.730,0;29.838,5;32.283,2;34.748,3;36.849,6;40.838,0;43.333,5;45.216,5;47.258,8;44.508,6', ' Comando do Exército;Pessoal e Encargos Sociais;8.003,2;9.884,3;11.176,8;11.025,3;11.761,1;12.954,1;14.701,5;15.948,2;18.152,9;20.127,2;22.252,8;23.482,6;23.813,8;25.587,2;27.699,5;30.637,8;32.052,3;35.266,9;37.864,4;40.390,3;42.245,4;42.214,3', ' Comando do Exército;Juros e Encargos da Dívida;107,8;92,5;47,8;15,6;17,8;14,4;10,5;6,7;3,3;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;;', ' Comando do Exército;Outras Despesas Correntes;523,3;589,4;523,5;621,3;745,1;981,0;999,4;1.073,0;1.312,5;1.445,4;1.925,0;2.238,8;2.202,4;2.670,3;3.255,1;3.200,9;3.676,8;4.012,9;3.966,5;3.313,1;3.661,1;1.709,4', ' Comando do Exército;Investimentos;143,6;148,6;267,2;86,7;114,0;95,2;121,6;227,0;370,9;567,0;795,5;1.117,4;2.713,8;1.581,1;1.328,6;909,6;1.120,5;1.558,2;1.502,7;1.513,1;1.352,3;584,9', ' Comando do Exército;Inversões Financeiras;0,0;20,0;1,5;11,7;1,7;1,7;49,7;41,8;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0', ' Comando do Exército;Amortização da Dívida;294,9;450,3;711,6;46,4;57,4;50,8;37,4;24,7;13,1;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0', ' Comando da Marinha;TOTAL;5.064,2;6.097,8;6.760,0;6.235,2;6.402,3;7.206,4;7.887,7;8.781,6;10.509,6;12.612,6;16.037,6;16.327,4;17.455,2;19.095,4;20.228,0;20.804,1;21.062,2;24.335,8;28.934,3;33.243,5;27.591,8;25.324,1', ' Comando da Marinha;Pessoal e Encargos Sociais;3.899,5;4.758,5;5.527,0;5.382,6;5.684,3;6.264,3;7.137,4;7.744,4;9.012,9;10.145,7;11.253,0;11.927,0;12.314,7;13.508,7;14.505,9;16.136,9;16.849,8;18.555,9;20.026,7;21.398,5;22.355,0;22.279,9', ' Comando da Marinha;Juros e Encargos da Dívida;116,3;136,2;72,6;27,9;14,1;8,2;5,6;2,7;1,1;55,1;48,6;103,1;138,5;183,3;217,9;213,5;168,3;161,8;188,8;180,7;310,9;106,2', ' Comando da Marinha;Outras Despesas Correntes;440,8;541,1;452,6;527,9;496,6;776,1;486,9;660,6;940,9;1.046,4;1.001,6;1.348,2;1.333,2;1.309,7;1.804,3;1.645,5;1.631,9;2.022,6;2.091,7;1.737,8;1.860,0;1.230,7', ' Comando da Marinha;Investimentos;110,5;77,5;20,9;28,4;31,5;41,3;202,5;341,9;538,7;1.358,5;3.733,1;2.780,8;3.315,7;3.505,1;2.872,3;1.733,6;1.519,8;2.581,4;2.906,6;1.979,8;1.920,5;1.239,3', ' Comando da Marinha;Inversões Financeiras;0,1;0,2;0,5;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;215,0;2.885,0;7.150,0;;', ' Comando da Marinha;Amortização da Dívida;497,0;584,3;686,5;268,3;175,9;116,6;55,4;32,1;16,1;6,9;1,3;168,2;353,3;588,6;827,6;1.074,6;892,4;799,1;835,4;796,8;1.145,4;468,0', 'Secretaria da Comissão Interministerial para os Recursos do Mar;TOTAL;6,8;4,4;3,2;3,1;5,6;6,5;21,3;21,7;63,4;102,0;20,2;16,4;62,0;64,7;13,9;41,0;123,6;33,0;55,5;37,7;25,4;17,0', 'Secretaria da Comissão Interministerial para os Recursos do Mar;Outras Despesas Correntes;5,0;3,7;3,0;2,9;5,2;5,6;16,9;15,8;59,4;94,3;13,8;12,9;46,9;53,0;9,1;10,7;11,7;8,0;13,6;15,0;9,8;1,7', 'Secretaria da Comissão Interministerial para os Recursos do Mar;Investimentos;1,8;0,7;0,1;0,1;0,4;0,9;4,4;5,9;4,0;7,7;6,4;3,5;15,1;11,7;4,8;30,3;111,9;25,0;41,9;22,6;15,6;15,3', 'Caixa de Financiamento Imobiliário da Aeronáutica;TOTAL;9,0;13,5;6,4;3,4;6,3;9,1;8,3;9,0;6,8;10,4;4,7;2,4;2,4;2,5;5,0;2,4;3,6;2,5;2,7;3,6;4,0;2,2', 'Caixa de Financiamento Imobiliário da Aeronáutica;Pessoal e Encargos Sociais;0,2;0,2;0,2;0,6;0,7;0,6;0,4;0,5;0,6;0,7;1,0;0,9;1,0;1,1;3,3;1,3;1,3;1,4;1,4;1,4;1,5;1,4', 'Caixa de Financiamento Imobiliário da Aeronáutica;Juros e Encargos da Dívida;3,7;3,0;3,9;0,5;1,1;1,4;1,0;1,0;1,0;1,1;0,5;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;;', 'Caixa de Financiamento Imobiliário da Aeronáutica;Outras Despesas Correntes;0,3;0,3;0,5;0,5;0,6;0,7;0,6;0,8;1,4;1,4;1,6;1,3;1,3;1,3;1,5;1,0;1,3;1,0;1,1;2,0;2,3;0,8', 'Caixa de Financiamento Imobiliário da Aeronáutica;Investimentos;3,1;4,0;0,0;0,0;0,1;0,1;0,1;0,2;0,2;0,1;0,0;0,0;0,1;0,0;0,1;0,1;0,1;0,1;0,2;0,2;0,3;0,0', 'Caixa de Financiamento Imobiliário da Aeronáutica;Inversões Financeiras;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,9;0,0;0,0;0,0;0,0;0,0', 'Caixa de Financiamento Imobiliário da Aeronáutica;Amortização da Dívida;1,7;6,0;1,9;1,8;3,9;6,3;6,2;6,6;3,6;7,1;1,5;0,1;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0', 'Indústria de Material Bélico do Brasil;TOTAL;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;131,8;187,8;190,8;199,2;181,9;229,3;232,7;212,6;218,3;233,5;236,7;228,8;211,4;140,3', 'Indústria de Material Bélico do Brasil;Pessoal e Encargos Sociais;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;27,3;45,8;49,0;51,5;55,9;68,9;73,3;83,2;85,2;92,7;89,8;95,8;95,4 ;93,3 ', 'Indústria de Material Bélico do Brasil;Juros e Encargos da Dívida;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,4;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;;', 'Indústria de Material Bélico do Brasil;Outras Despesas Correntes;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;78,4;124,4;123,7;126,6;105,7;129,4;141,7;119,6;126,1;126,7;141,4;118,9;103,8 ;44,3 ', 'Indústria de Material Bélico do Brasil;Investimentos;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;22,9;14,5;18,1;21,1;20,3;31,0;17,7;9,8;7,0;14,1;5,5;14,1;12,2 ;2,8 ', 'Indústria de Material Bélico do Brasil;Amortização da Dívida;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;3,2;2,7;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0', 'Fundação Osório;TOTAL;3,4;3,7;4,0;4,5;5,4;5,8;7,6;8,4;9,4;9,7;11,2;11,5;12,2;13,5;15,7;16,9;19,4;22,1;22,3;24,2;23,9;22,3', 'Fundação Osório;Pessoal e Encargos Sociais;1,9;2,0;2,3;2,5;2,8;3,0;4,5;5,2;5,8;6,7;7,0;7,3;7,8;8,8;10,3;11,2;12,6;14,2;15,3;16,3;17,1;16,4', 'Fundação Osório;Outras Despesas Correntes;1,4;1,6;1,5;1,9;2,1;2,4;2,4;2,7;3,4;2,9;3,8;3,8;4,3;4,5;5,1;5,6;6,7;7,4;6,5;6,4;6,6;5,8', 'Fundação Osório;Investimentos;0,1;0,1;0,2;0,1;0,5;0,4;0,7;0,4;0,2;0,1;0,4;0,4;0,1;0,1;0,3;0,1;0,1;0,5;0,5;1,4;0,2;0,1', 'Caixa de Construções de Casas para o Pessoal da Marinha;TOTAL;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;15,0;11,0;12,5;17,1;13,3;16,0;21,1;22,3;31,4;37,3;81,0;41,1', 'Caixa de Construções de Casas para o Pessoal da Marinha;Pessoal e Encargos Sociais;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;2,1;2,0;2,1;2,1;2,2;2,3;2,3;2,4;2,5;2,6;2,5;2,5', 'Caixa de Construções de Casas para o Pessoal da Marinha;Juros e Encargos da Dívida;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,9;0,5;0,9;0,3;0,5;0,2;2,5;4,6;3,7;3,7;3,7', 'Caixa de Construções de Casas para o Pessoal da Marinha;Outras Despesas Correntes;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;12,0;7,8;9,0;10,4;10,1;9,0;8,2;8,0;8,5;6,8;8,6;5,9', 'Caixa de Construções de Casas para o Pessoal da Marinha;Investimentos;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,9;0,3;0,5;0,2;0,0;0,0;0,1;0,0;0,0;0,1;0,0;0,0', 'Caixa de Construções de Casas para o Pessoal da Marinha;Inversões Financeiras;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;2,8;0,0;0,0;7,9;0,0;0,0;8,1;50,4;13,3', 'Caixa de Construções de Casas para o Pessoal da Marinha;Amortização da Dívida;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,4;0,7;0,7;4,2;2,4;9,4;15,8;16,1;15,7;15,7', 'Amazônia Azul Tecnologias de Defesa S.A;TOTAL;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;51,2;185,4;250,8;299,6;320,0;333,1;371,3;343,1;322,5', 'Amazônia Azul Tecnologias de Defesa S.A;Pessoal e Encargos Sociais;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;40,8;169,0;215,9;264,8;285,0;300,1;333,6;305,4;304,9', 'Amazônia Azul Tecnologias de Defesa S.A;Outras Despesas Correntes;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;8,1;15,9;34,1;34,4;34,7;32,6;37,2;35,8;17,5', 'Amazônia Azul Tecnologias de Defesa S.A;Investimentos;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;2,2;0,5;0,8;0,4;0,3;0,4;0,5;1,9;0,0', 'Fundo do Ministério da Defesa;TOTAL;3,5;2,7;1,7;5,9;3,1;3,6;3,9;3,0;0,6;1,6;1,2;1,3;2,6;1,5;2,6;2,2;2,8;3,8;3,0;3,2;3,1;1,6', 'Fundo do Ministério da Defesa;Outras Despesas Correntes;2,9;2,0;1,2;4,4;1,5;1,8;2,0;1,6;0,6;1,2;1,2;1,2;2,5;1,5;2,3;2,2;2,8;3,8;2,9;3,1;3,1;1,6', 'Fundo do Ministério da Defesa;Investimentos;0,7;0,8;0,6;1,5;1,6;1,9;1,8;1,4;0,0;0,4;0,0;0,1;0,1;0,0;0,3;0,0;0,0;0,0;0,1;0,0;0,0;0,0', 'Fundo de Administração do Hospital das Forças Armadas;TOTAL;20,5;40,0;61,4;52,5;67,3;79,5;93,2;90,0;98,4;119,0;180,2;209,1;210,7;217,5;236,4;243,8;237,7;238,4;250,0;268,3;272,8;179,8', 'Fundo de Administração do Hospital das Forças Armadas;Pessoal e Encargos Sociais;0,0;12,7;43,2;25,3;26,4;34,8;42,5;44,3;55,8;74,7;106,9;118,1;128,6;140,4;147,8;151,6;160,7;168,9;166,7;166,0;166,9;141,5', 'Fundo de Administração do Hospital das Forças Armadas;Outras Despesas Correntes;20,5;27,1;18,0;25,7;32,4;32,4;40,2;42,2;39,8;40,9;56,9;77,4;75,5;74,3;83,1;84,6;74,0;65,7;75,7;94,9;85,8;37,2', 'Fundo de Administração do Hospital das Forças Armadas;Investimentos;0,1;0,3;0,3;1,5;8,5;12,3;10,6;3,5;2,8;3,4;16,4;13,5;6,7;2,9;5,5;7,6;3,0;3,8;7,7;7,4;20,0;1,1', 'Fundo Serviço Militar;TOTAL;5,2;5,6;5,0;4,8;6,0;5,2;5,4;5,4;5,0;5,5;6,9;7,1;7,2;6,7;6,7;5,7;6,4;5,4;7,5;9,2;9,1;3,7', 'Fundo Serviço Militar;Outras Despesas Correntes;4,1;4,5;4,0;3,9;4,5;4,5;4,4;4,8;4,1;4,7;5,9;6,1;6,1;5,4;5,1;4,9;5,4;4,6;6,7;7,0;7,4;2,7', 'Fundo Serviço Militar;Investimentos;1,1;1,1;1,0;1,0;1,5;0,7;1,0;0,7;0,9;0,9;1,0;1,0;1,1;1,3;1,6;0,8;1,0;0,8;0,8;2,2;1,7;1,1', 'Fundo Aeronáutico;TOTAL;933,7;772,5;787,3;686,3;999,4;1.003,9;1.199,4;1.256,8;1.453,6;1.545,7;1.985,9;1.817,8;1.605,8;1.969,1;2.400,0;2.202,3;2.372,0;2.804,1;3.001,7;3.103,9;3.135,6;1.865,8', 'Fundo Aeronáutico;Outras Despesas Correntes;330,8;397,0;408,8;442,4;638,5;629,0;726,4;671,8;625,0;847,4;974,8;993,4;1.049,5;1.319,6;1.594,9;1.466,1;1.488,5;1.906,0;2.067,0;2.332,1;2.522,6;1.481,9', 'Fundo Aeronáutico;Investimentos;602,9;375,6;378,6;243,3;360,9;373,8;471,5;582,7;825,7;695,4;1.008,4;820,9;552,6;646,6;801,7;730,9;880,3;893,1;929,6;767,0;608,5;383,9', 'Fundo Aeronáutico;Inversões Financeiras;0,0;0,0;0,0;0,7;0,0;1,1;1,5;2,2;3,0;2,9;2,7;3,6;3,7;2,9;3,5;5,3;3,2;5,0;5,0;4,8;4,5;0,0', 'Fundo do Exército;TOTAL;257,5;284,8;347,6;322,7;426,0;462,4;545,9;573,2;661,8;784,8;827,1;924,6;1.042,7;1.080,3;1.121,0;1.240,1;1.103,4;1.300,0;1.730,9;2.732,0;2.305,3;1.036,1', 'Fundo do Exército;Outras Despesas Correntes;223,8;238,2;307,0;296,5;360,7;416,7;503,5;524,5;612,9;733,7;763,9;824,7;904,0;934,6;992,4;1.158,1;1.051,5;1.188,3;1.568,7;2.577,4;2.189,7;986,8', 'Fundo do Exército;Investimentos;33,8;46,6;40,6;26,2;65,3;45,6;42,4;48,8;48,9;51,1;63,2;99,9;138,5;145,6;128,7;82,0;51,9;111,7;162,3;154,6;115,6;49,3', 'Fundo do Exército;Inversões Financeiras;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,1;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0', 'Fundo Naval;TOTAL;447,3;542,5;289,1;226,2;369,4;309,3;350,4;454,0;309,2;350,1;390,5;304,4;434,7;506,9;522,6;607,5;732,8;785,5;635,1;1.277,4;1.112,1;693,4', 'Fundo Naval;Outras Despesas Correntes;356,3;415,6;266,2;202,0;320,5;280,9;326,8;321,3;246,8;291,8;306,1;255,7;354,8;458,2;451,6;514,0;693,5;738,6;458,8;1.143,2;1.039,5;643,8', 'Fundo Naval;Investimentos;91,0;126,5;22,9;24,2;49,0;28,4;23,5;132,7;62,4;57,3;83,7;48,7;64,9;48,7;71,0;93,5;39,3;46,9;176,3;134,2;72,6;49,6', 'Fundo Naval;Inversões Financeiras;0,0;0,3;0,0;0,0;0,0;0,0;0,0;0,0;0,0;1,1;0,8;;15,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0;0,0', 'Fundo de Desenvolvimento do Ensino Profissional Marítimo;TOTAL;27,3;33,4;22,2;23,6;39,7;47,9;55,2;78,1;71,3;80,9;96,0;81,1;124,0;85,4;140,2;95,4;78,4;76,3;60,1;63,3;69,8;43,3', 'Fundo de Desenvolvimento do Ensino Profissional Marítimo;Outras Despesas Correntes;24,8;31,2;20,3;22,3;36,7;43,2;52,0;71,7;67,3;76,0;83,4;74,5;109,4;80,4;138,4;94,4;77,1;75,1;59,1;62,0;67,6;42,5', 'Fundo de Desenvolvimento do Ensino Profissional Marítimo;Investimentos;2,5;2,2;1,9;1,3;3,0;4,8;3,2;6,4;4,0;4,9;12,6;6,6;14,6;5,0;1,8;1,0;1,3;1,2;1,0;1,3;2,2;0,8', '* ATÉ O MÊS DE JUNHO DE 2020;;;;;;;;;;;;;;;;;;;;;;;', 'Fonte: SIAFI.;;;;;;;;;;;;;;;;;;;;;;;', ';;;;;;;;;;;;;;;;;;;;;;;', ';;;;;;;;;;;;;;;;;;;;;;;', ';;;;;;;;;;;;;;;;;;;;;;;', ';;;;;;;;;;;;;;;;;;;;;;;', ';;;;;;;;;;;;;;;;;;;;;;;', ';;;;;;;;;;;;;;;;;;;;;;;', ';;;;;;;;;;;;;;;;;;;;;;;', ';;;;;;;;;;;;;;;;;;;;;;;', '']

Vendo rápido parece que está tudo bem, mas tem algo estranho no final. Vamos tentar carregar o arquivo pra verificar se está bem formatado.

In [3]:
# 1 - encoding
# 2 - separador
df_md = pd.read_csv("../datasets/md_bruto.csv", delimiter=";", encoding="latin")

Agora podemos ver a formatação automática.

In [4]:
df_md

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2012,2013,2014,2015,2016,2017,2018,2019,Dotação atualizada 2020*,Empenhado
0,Total Ministério da Defesa,TOTAL,"20.696,4","25.494,0","28.176,2","25.777,8","28.513,2","33.021,6","35.581,1","39.766,7",...,"66.378,8","70.881,0","76.874,2","81.873,5","84.508,9","93.120,1","102.938,3","111.998,3","108.879,6","87.786,1"
1,Total Ministério da Defesa,Pessoal e Encargos Sociais,"15.119,8","18.724,1","21.332,9","21.111,5","22.612,4","24.856,8","28.522,1","30.734,0",...,"47.270,9","51.261,8","55.591,8","61.566,2","64.356,8","70.740,1","76.018,8","81.102,9","84.718,8","74.853,1"
2,Total Ministério da Defesa,Juros e Encargos da Dívida,"322,4","390,1","632,1","460,7","411,2","1.318,6","338,0","178,3",...,"234,7","318,9","386,8","402,3","335,3","373,0","469,0","497,0","828,2","316,0"
3,Total Ministério da Defesa,Outras Despesas Correntes,"2.493,5","2.983,5","2.665,2","2.793,8","3.520,4","4.214,0","4.197,3","4.735,1",...,"8.206,7","9.376,8","11.196,8","10.676,6","11.448,1","12.019,7","13.079,7","13.976,9","14.302,1","7.222,7"
4,Total Ministério da Defesa,Investimentos,"1.716,3","1.947,8","1.686,4","878,8","1.549,1","1.917,5","1.757,7","2.669,1",...,"10.033,7","8.956,7","8.258,2","7.239,9","6.949,1","8.518,4","9.104,9","7.878,5","7.131,6","4.514,5"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

E como ficou o final que vimos antes? Não deu nenhum erro, então algo deve ter acontecido.

In [5]:
df_md.tail()

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2012,2013,2014,2015,2016,2017,2018,2019,Dotação atualizada 2020*,Empenhado
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Nossa análise pode ficar prejudicada com tantos valores faltando, então cada registro em que o número de `NaN`s passar de 10 será apagado

In [6]:
# axis | 0 = linha, 1 = coluna
# how | any, all
# thresh | número de NaNs
df = df_md.dropna(axis=0, how="any", thresh=10)
df

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2012,2013,2014,2015,2016,2017,2018,2019,Dotação atualizada 2020*,Empenhado
0,Total Ministério da Defesa,TOTAL,"20.696,4","25.494,0","28.176,2","25.777,8","28.513,2","33.021,6","35.581,1","39.766,7",...,"66.378,8","70.881,0","76.874,2","81.873,5","84.508,9","93.120,1","102.938,3","111.998,3","108.879,6","87.786,1"
1,Total Ministério da Defesa,Pessoal e Encargos Sociais,"15.119,8","18.724,1","21.332,9","21.111,5","22.612,4","24.856,8","28.522,1","30.734,0",...,"47.270,9","51.261,8","55.591,8","61.566,2","64.356,8","70.740,1","76.018,8","81.102,9","84.718,8","74.853,1"
2,Total Ministério da Defesa,Juros e Encargos da Dívida,"322,4","390,1","632,1","460,7","411,2","1.318,6","338,0","178,3",...,"234,7","318,9","386,8","402,3","335,3","373,0","469,0","497,0","828,2","316,0"
3,Total Ministério da Defesa,Outras Despesas Correntes,"2.493,5","2.983,5","2.665,2","2.793,8","3.520,4","4.214,0","4.197,3","4.735,1",...,"8.206,7","9.376,8","11.196,8","10.676,6","11.448,1","12.019,7","13.079,7","13.976,9","14.302,1","7.222,7"
4,Total Ministério da Defesa,Investimentos,"1.716,3","1.947,8","1.686,4","878,8","1.549,1","1.917,5","1.757,7","2.669,1",...,"10.033,7","8.956,7","8.258,2","7.239,9","6.949,1","8.518,4","9.104,9","7.878,5","7.131,6","4.514,5"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Fundo Naval,Investimentos,"91,0","126,5","22,9","24,2","49,0","28,4","23,5","132,7",...,"64,9","48,7","71,0","93,5","39,3","46,9","176,3","134,2","72,6","49,6"
87,Fundo Naval,Inversões Financeiras,"0,0","0,3","0,0","0,0","0,0","0,0","0,0","0,0",...,"15,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
88,Fundo de Desenvolvimento do Ensino Profissiona...,TOTAL,"27,3","33,4","22,2","23,6","39,7","47,9","55,2","78,1",...,"124,0","85,4","140,2","95,4","78,4","76,3","60,1","63,3","69,8","43,3"
89,Fundo de Desenvolvimento do Ensino Profissiona...,Outras Despesas Correntes,"24,8","31,2","20,3","22,3","36,7","43,2","52,0","71,7",...,"109,4","80,4","138,4","94,4","77,1","75,1","59,1","62,0","67,6","42,5"
90,Fundo de Desenvolvimento do Ensino Profissiona...,Investimentos,"2,5","2,2","1,9","1,3","3,0","4,8","3,2","6,4",...,"14,6","5,0","1,8","1,0","1,3","1,2","1,0","1,3","2,2","0,8"

As duas últimas colunas fogem um pouco do valor inteiro por ano, então vamos tirar elas dessa análise.

In [7]:
df = df.drop(["Dotação atualizada 2020*", "Empenhado"], axis=1)
df = df.fillna(0)
df

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Total Ministério da Defesa,TOTAL,"20.696,4","25.494,0","28.176,2","25.777,8","28.513,2","33.021,6","35.581,1","39.766,7",...,"59.452,3","61.663,1","66.378,8","70.881,0","76.874,2","81.873,5","84.508,9","93.120,1","102.938,3","111.998,3"
1,Total Ministério da Defesa,Pessoal e Encargos Sociais,"15.119,8","18.724,1","21.332,9","21.111,5","22.612,4","24.856,8","28.522,1","30.734,0",...,"43.648,9","46.449,1","47.270,9","51.261,8","55.591,8","61.566,2","64.356,8","70.740,1","76.018,8","81.102,9"
2,Total Ministério da Defesa,Juros e Encargos da Dívida,"322,4","390,1","632,1","460,7","411,2","1.318,6","338,0","178,3",...,"103,8","226,3","234,7","318,9","386,8","402,3","335,3","373,0","469,0","497,0"
3,Total Ministério da Defesa,Outras Despesas Correntes,"2.493,5","2.983,5","2.665,2","2.793,8","3.520,4","4.214,0","4.197,3","4.735,1",...,"7.304,2","8.088,5","8.206,7","9.376,8","11.196,8","10.676,6","11.448,1","12.019,7","13.079,7","13.976,9"
4,Total Ministério da Defesa,Investimentos,"1.716,3","1.947,8","1.686,4","878,8","1.549,1","1.917,5","1.757,7","2.669,1",...,"8.241,3","6.529,5","10.033,7","8.956,7","8.258,2","7.239,9","6.949,1","8.518,4","9.104,9","7.878,5"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,Fundo Naval,Investimentos,"91,0","126,5","22,9","24,2","49,0","28,4","23,5","132,7",...,"83,7","48,7","64,9","48,7","71,0","93,5","39,3","46,9","176,3","134,2"
87,Fundo Naval,Inversões Financeiras,"0,0","0,3","0,0","0,0","0,0","0,0","0,0","0,0",...,"0,8",0,"15,0","0,0","0,0","0,0","0,0","0,0","0,0","0,0"
88,Fundo de Desenvolvimento do Ensino Profissiona...,TOTAL,"27,3","33,4","22,2","23,6","39,7","47,9","55,2","78,1",...,"96,0","81,1","124,0","85,4","140,2","95,4","78,4","76,3","60,1","63,3"
89,Fundo de Desenvolvimento do Ensino Profissiona...,Outras Despesas Correntes,"24,8","31,2","20,3","22,3","36,7","43,2","52,0","71,7",...,"83,4","74,5","109,4","80,4","138,4","94,4","77,1","75,1","59,1","62,0"
90,Fundo de Desenvolvimento do Ensino Profissiona...,Investimentos,"2,5","2,2","1,9","1,3","3,0","4,8","3,2","6,4",...,"12,6","6,6","14,6","5,0","1,8","1,0","1,3","1,2","1,0","1,3"

Agora com tudo formatado, vamos aplicar um agrupamento.

In [8]:
df.groupby("GRUPO DE DESPESA").sum()

,Unidade Orçamentária,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2012,2013,2014,2015,2016,2017,2018,2019
GRUPO DE DESPESA,,,,,,,,,,,,,,,,,,,,
Amortização da Dívida,Total Ministério da DefesaAdministração Direta...,"1.044,2111,8138,8294,9497,01,70,00,0","1.428,1200,5187,0450,3584,36,00,00,0","1.857,5160,4297,2711,6686,51,90,00,0","520,751,6152,546,4268,31,80,00,0","418,350,6130,557,4175,93,90,00,0","711,9239,5298,750,8116,66,30,00,0","714,9410,3205,637,455,46,20,00,0","841,1293,0484,724,732,16,60,00,0","215,00,0179,013,116,13,63,20,0","171,50,0154,80,06,97,12,70,0","150,60,0147,80,01,31,50,00,0","614,10,0260,50,0353,30,00,00,4","961,00,0371,60,0588,60,00,00,7","1.342,90,0514,60,0827,60,00,00,7","1.686,90,0608,10,01.074,60,00,04,2","1.289,80,0395,00,0892,40,00,02,4","1.210,10,0401,60,0799,10,00,09,4","1.375,90,0524,70,0835,40,00,015,8","1.380,20,0567,40,0796,80,00,016,1"
Inversões Financeiras,Total Ministério da DefesaAdministração Direta...,"0,10,00,00,10,00,00,00,00,0","20,50,020,00,20,00,00,00,00,3","2,00,01,50,50,00,00,00,00,0","12,40,011,70,00,00,00,70,00,0","1,80,01,70,00,00,00,00,00,0","2,80,01,70,00,00,01,10,00,0","51,20,049,70,00,00,01,50,00,0","609,2565,141,80,00,00,02,20,00,0","81,078,00,00,00,00,03,00,00,0","4,00,00,00,00,00,02,90,01,1","3,50,00,00,00,00,02,70,00,8","18,70,00,00,00,00,03,70,115,0","5,70,00,00,00,02,82,90,00,0","97,794,20,00,00,00,03,50,00,0","301,6296,30,00,00,00,05,30,00,0","129,8117,80,00,00,97,93,20,00,0","258,838,80,0215,00,00,05,00,00,0","2.890,00,00,02.885,00,00,05,00,00,0","7.162,80,00,07.150,00,08,14,80,00,0"
Investimentos,Total Ministério da DefesaAdministração Direta...,"1.716,3600,3125,1143,6110,51,83,10,00,10,00,00...","1.947,8383,7780,1148,677,50,74,00,00,10,00,00,...","1.686,4329,3622,9267,220,90,10,00,00,20,00,00,...","878,8124,9339,586,728,40,10,00,00,10,00,01,51,...","1.549,1152,2760,8114,031,50,40,10,00,50,00,01,...","1.917,5646,4665,795,241,30,90,10,00,40,00,01,9...","1.757,7216,4658,0121,6202,54,40,10,00,70,00,01...","2.669,1366,5951,2227,0341,95,90,20,00,40,00,01...","3.406,7275,81.249,4370,9538,74,00,222,90,20,00...","4.798,4455,01.582,3567,01.358,57,70,114,50,10,...","8.241,3991,81.509,7795,53.733,16,40,018,10,40,...","10.033,71.287,11.902,52.713,83.315,715,10,120,...","8.956,71.180,61.794,61.581,13.505,111,70,031,0...","8.258,21.390,11.633,51.328,62.872,34,80,117,70...","7.239,9977,12.662,7909,61.733,630,30,19,80,10,...","6.949,11.043,62.168,81.120,51.519,8111,90,17,0...","8.518,4819,12.462,21.558,22.581,425,00,114,10,...","9.104,91.030,12.339,21.502,72.906,641,90,25,50...","7.878,5855,02.425,01.513,11.979,822,60,214,11,..."
Juros e Encargos da Dívida,Total Ministério da DefesaAdministração Direta...,"322,429,665,0107,8116,33,70,00,0","390,142,0116,492,5136,23,00,00,0","632,1234,4273,547,872,63,90,00,0","460,7349,167,515,627,90,50,00,0","411,2335,742,517,814,11,10,00,0","1.318,6290,11.004,514,48,21,40,00,0","338,0240,880,210,55,61,00,00,0","178,3101,366,76,72,71,00,00,0","56,50,051,03,31,11,00,00,0","330,60,0274,00,055,11,10,40,0","103,80,054,70,048,60,50,00,0","234,70,095,70,0138,50,00,00,5","318,90,0134,80,0183,30,00,00,9","386,80,0168,60,0217,90,00,00,3","402,30,0188,30,0213,50,00,00,5","335,30,0166,80,0168,30,00,00,2","373,00,0208,70,0161,80,00,02,5","469,00,0275,60,0188,80,00,04,6","497,00,0312,60,0180,70,00,03,7"
Outras Despesas Correntes,Total Ministério da DefesaAdministração Direta...,"2.493,550,6508,8523,3440,85,00,30,01,40,00,02,...","2.983,559,8672,1589,4541,13,70,30,01,60,00,02,...","2.665,273,0585,8523,5452,63,00,50,01,50,00,01,...","2.793,854,8587,3621,3527,92,90,50,01,90,00,04,...","3.520,4151,9724,4745,1496,65,20,60,02,10,00,01...","4.214,0221,6818,4981,0776,15,60,70,02,40,00,01...","4.197,3260,5775,3999,4486,916,90,60,02,40,00,0...","4.735,1249,11.095,31.073,0660,615,80,80,02,70,...","5.533,5373,01.168,01.312,5940,959,41,478,43,40...","6.282,5408,21.164,11.445,41.046,494,31,4124,42...","7.304,2798,81.231,81.925,01.001,613,81,6123,73...","8.206,7521,31.480,92.202,41.333,246,91,3105,74...","9.376,8658,51.657,72.670,31.309,753,01,3129,44...","11.196,8903,01.783,13.255,11.804,39,11,5141,75...","10.676,6760,01.565,93.200,91.645,510,71,0119,6...","11.448,1967,31.590,93.676,81.631,911,71,3126,1...","12.019,7531,81.284,54.012,92.022,68,01,0126,77...","13.079,7969,21.609,73.966,52.091,713,61,1141,4...","13.976,9877,71.642,23.313,11.737,815,02,0118,9..."
Pessoal e Encargos Sociais,Total Ministério da DefesaAdministração Direta...,"15.119,838,13.177,08.003,23.899,50,20,01,90,00...","18.724,134,94.031,59.884,34.758,50,20,02,00,00...","21.332,928,74.554,811.176,85.527,00,20,02,30,0...","21.111,538,84.636,511.025,35.382,60,60,02,50,0...","22.612,4186,14.951,011.761,15.684,30,70,02,80,...","24.856,8198,05.402,112.954,16.264,30,60,03,00,...","28.522,1293,36.342,614.701,57.137,40,40,04,50,...","30.734,034,36.957,015.948,27.744,40,50,05,20,0...","35.328,638,68.034,918.152,99.012,90,627,35,80,...","39.403,141,68.960,620.127,210.145,70,745,86,70...","43.648,945,59.931,622.252,811.253,01,049,07,02...","47.270,960,410.886,723.813,812.314,71,055,97,8...","51.261,869,511.834,325.587,213.508,71,168,98,8...","55.591,880,212.900,327.699,514.505,93,373,310,...","61.566,286,414.239,630.637,816.136,91,383,211,...","64.356,886,514.841,332.052,316.849,81,385,212,...","70.740,185,416.267,335.266,918.555,91,492,714,...","76.018,887,617.464,237.864,420.026,71,489,815,...","81.102,991,418.606,840.390,321.398,51,495,816,..."
TOTAL,Total Ministério da DefesaAdministração Direta...,"20.696,4830,44.014,79.072,85.064,26,89,00,03,4...","25.494,0720,95.787,111.185,16.097,84,413,50,03...","28.176,2825,76.334,212.728,46.760,03,26,40,04,...","25.777,8619,35.783,311.807,06.235,23,13,40,04,...","28.513,2876,56.609,112.697,16.402,35,66,30,05,...","33.021,61.595,58.189,414.097,27.206,46,59,10,0...","35.581,11.421,38.061,615.920,17.887,721,38,30,...","39.766,71.609,39.554,917.321,48.781,621,79,00,...","44.621,3765,410.682,319.852,710.509,663,46,813...","50.990,2904,712.135,822.139,512.612,6102,010,4...","59.452,31.836,212.875,524.973,316.037,620,24,7...","66.378,81.868,714.626,328.730,017.455,262,02,4...","70.881,01.908,615.793,029.838,519.095,464,72,5...","76.874,22.467,517.000,132.283,220.228,013,95,0...","81.873,52.119,819.264,634.748,320.804,141,02,4...","84.508,92.215,219.162,836.849,621.062,2123,63,...","93.120,11.475,120.624,340.838,024.335,833,02,5...","102.938,32.087,022.213,343.333,528.934,355,52,...","111.998,31.824,123.554,045.216,533.243,537,73,..."

Tem algo muito errado com nossos dados númericos. Vamos ver o comportamento da soma sem o agrupamento.

In [9]:
print(df["2000"][0])
print(df["2001"][0])
print(df["2000"][0] + df["2001"][0])

20.696,4
25.494,0
20.696,425.494,0

Ficou claro que é uma questão de formatação inadequada, então vamos usar uma função para converter de string para números.

In [10]:
colunas = [str(i) for i in range(2000, 2020)] 
print(colunas)
df[colunas].astype(float)

['2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']

ValueError: could not convert string to float: '20.696,4'

O erro acima mostra o por que o pandas não conseguiu converter os números sozinho quando leu o arquivo. O formato decimal usado pelo pandas é diferente do que usamos no Brasil. Vamos retirar os pontos e trocar as vírgulas por pontos e tentar de novo.

In [11]:
df[colunas] = df[colunas].replace(r'\.',"",regex=True).replace(r'\,',".",regex=True)
df[colunas] = df[colunas].astype(float)
print(df["2000"][0])
print(df["2001"][0])
print(df["2000"][0] + df["2001"][0])
df.dtypes

20696.4
25494.0
46190.4

Unidade Orçamentária      object
GRUPO DE DESPESA          object
2000                     float64
2001                     float64
2002                     float64
2003                     float64
2004                     float64
2005                     float64
2006                     float64
2007                     float64
2008                     float64
2009                     float64
2010                     float64
2011                     float64
2012                     float64
2013                     float64
2014                     float64
2015                     float64
2016                     float64
2017                     float64
2018                     float64
2019                     float64
dtype: object

Vamos ver o começo do DataFrame para ver se tudo está em ordem.

In [12]:
df.head()

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Total Ministério da Defesa,TOTAL,20696.4,25494.0,28176.2,25777.8,28513.2,33021.6,35581.1,39766.7,...,59452.3,61663.1,66378.8,70881.0,76874.2,81873.5,84508.9,93120.1,102938.3,111998.3
1,Total Ministério da Defesa,Pessoal e Encargos Sociais,15119.8,18724.1,21332.9,21111.5,22612.4,24856.8,28522.1,30734.0,...,43648.9,46449.1,47270.9,51261.8,55591.8,61566.2,64356.8,70740.1,76018.8,81102.9
2,Total Ministério da Defesa,Juros e Encargos da Dívida,322.4,390.1,632.1,460.7,411.2,1318.6,338.0,178.3,...,103.8,226.3,234.7,318.9,386.8,402.3,335.3,373.0,469.0,497.0
3,Total Ministério da Defesa,Outras Despesas Correntes,2493.5,2983.5,2665.2,2793.8,3520.4,4214.0,4197.3,4735.1,...,7304.2,8088.5,8206.7,9376.8,11196.8,10676.6,11448.1,12019.7,13079.7,13976.9
4,Total Ministério da Defesa,Investimentos,1716.3,1947.8,1686.4,878.8,1549.1,1917.5,1757.7,2669.1,...,8241.3,6529.5,10033.7,8956.7,8258.2,7239.9,6949.1,8518.4,9104.9,7878.5

Antes do nosso agrupamento, tem um pequeno errinho que podemos corrigir ainda. Vamos ver ele em ação utilizando um filtro.

In [13]:
indices_naval = df["Unidade Orçamentária"] == "Fundo Naval"
df[indices_naval]

KeyError: 'Unidade Orçamentária'

E agora vamos tirar o espaço extra que está no nome da coluna, e aplicar o filtro de novo.

In [14]:
df = df.rename(columns={"Unidade Orçamentária ": "Unidade Orçamentária"})

indices_naval = df["Unidade Orçamentária"] == "Fundo Naval"
df[indices_naval]

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
84,Fundo Naval,TOTAL,447.3,542.5,289.1,226.2,369.4,309.3,350.4,454.0,...,390.5,304.4,434.7,506.9,522.6,607.5,732.8,785.5,635.1,1277.4
85,Fundo Naval,Outras Despesas Correntes,356.3,415.6,266.2,202.0,320.5,280.9,326.8,321.3,...,306.1,255.7,354.8,458.2,451.6,514.0,693.5,738.6,458.8,1143.2
86,Fundo Naval,Investimentos,91.0,126.5,22.9,24.2,49.0,28.4,23.5,132.7,...,83.7,48.7,64.9,48.7,71.0,93.5,39.3,46.9,176.3,134.2
87,Fundo Naval,Inversões Financeiras,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0,...,0.8,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Vamos voltar ao primeiro agrupamento e ver as somas corretamente.

In [15]:
# SELECT * FROM md GROUP BY `GRUPO DE DESPESA` 
df.groupby("GRUPO DE DESPESA").sum()

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
GRUPO DE DESPESA,,,,,,,,,,,,,,,,,,,,
Amortização da Dívida,2088.4,2856.2,3715.1,1041.3,836.6,1423.8,1429.8,1682.2,430.0,343.0,301.2,732.2,1228.3,1921.9,2685.8,3373.8,2579.6,2420.2,2751.8,2760.5
Inversões Financeiras,0.2,41.0,4.0,24.8,3.5,5.6,102.4,1218.3,162.0,8.0,7.0,7.2,37.5,11.4,195.4,603.2,259.6,517.6,5780.0,14325.7
Investimentos,3432.9,3895.6,3372.9,1757.5,3098.4,3835.0,3515.4,5338.4,6813.5,9597.0,16482.5,13059.0,20067.4,17913.4,16516.7,14479.8,13898.2,17036.8,18209.8,15757.0
Juros e Encargos da Dívida,644.8,780.2,1264.3,921.3,822.4,2637.2,676.1,356.7,112.9,661.2,207.6,452.6,469.4,637.9,773.6,804.6,670.6,746.0,938.0,994.0
Outras Despesas Correntes,4986.9,5967.1,5330.6,5587.6,7041.1,8428.3,8394.6,9470.3,11067.0,12565.3,14608.5,16176.9,16413.5,18753.7,22393.5,21353.2,22896.2,24039.4,26159.4,27953.7
Pessoal e Encargos Sociais,30239.7,37448.2,42665.9,42223.1,45224.8,49713.7,57044.3,61467.9,70657.4,78806.1,87297.8,92898.3,94541.9,102523.6,111183.6,123132.4,128713.6,141480.2,152037.5,162205.6
TOTAL,41392.7,50988.0,56352.4,51555.6,57026.4,66043.3,71162.4,79533.5,89242.6,101980.3,118904.6,123326.3,132757.7,141762.2,153748.5,163747.0,169017.8,186240.2,205876.4,223996.6

E agora filtrando por somente um ano.

In [16]:
# SELECT 2019 FROM md GROUP BY `GRUPO DE DESPESA` 
df.groupby("GRUPO DE DESPESA").sum()[["2019"]]

                                2019
GRUPO DE DESPESA
Amortização da Dívida         2760.5
Inversões Financeiras        14325.7
Investimentos                15757.0
Juros e Encargos da Dívida     994.0
Outras Despesas Correntes    27953.7
Pessoal e Encargos Sociais  162205.6
TOTAL                       223996.6

Por fim, vamos mostrar ordenação baseado em um filtro.

In [17]:
#SELECT * FROM md WHERE `GRUPO DE DESPESA` == "TOTAL" ORDER BY "2019"
indices_total = df["GRUPO DE DESPESA"] == "TOTAL"
df[indices_total].sort_values("2019")

,Unidade Orçamentária,GRUPO DE DESPESA,2000,2001,2002,2003,2004,2005,2006,2007,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
66,Fundo do Ministério da Defesa,TOTAL,3.5,2.7,1.7,5.9,3.1,3.6,3.9,3.0,...,1.2,1.3,2.6,1.5,2.6,2.2,2.8,3.8,3.0,3.2
38,Caixa de Financiamento Imobiliário da Aeronáutica,TOTAL,9.0,13.5,6.4,3.4,6.3,9.1,8.3,9.0,...,4.7,2.4,2.4,2.5,5.0,2.4,3.6,2.5,2.7,3.6
73,Fundo Serviço Militar,TOTAL,5.2,5.6,5.0,4.8,6.0,5.2,5.4,5.4,...,6.9,7.1,7.2,6.7,6.7,5.7,6.4,5.4,7.5,9.2
51,Fundação Osório,TOTAL,3.4,3.7,4.0,4.5,5.4,5.8,7.6,8.4,...,11.2,11.5,12.2,13.5,15.7,16.9,19.4,22.1,22.3,24.2
55,Caixa de Construções de Casas para o Pessoal d...,TOTAL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,11.0,12.5,17.1,13.3,16.0,21.1,22.3,31.4,37.3
35,Secretaria da Comissão Interministerial para o...,TOTAL,6.8,4.4,3.2,3.1,5.6,6.5,21.3,21.7,...,20.2,16.4,62.0,64.7,13.9,41.0,123.6,33.0,55.5,37.7
88,Fundo de Desenvolvimento do Ensino Profissiona...,TOTAL,27.3,33.4,22.2,23.6,39.7,47.9,55.2,78.1,...,96.0,81.1,124.0,85.4,140.2,95.4,78.4,76.3,60.1,63.3
45,Indústria de Material Bélico do Brasil,TOTAL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,190.8,199.2,181.9,229.3,232.7,212.6,218.3,233.5,236.7,228.8
69,Fundo de Administração do Hospital das Forças ...,TOTAL,20.5,40.0,61.4,52.5,67.3,79.5,93.2,90.0,...,180.2,209.1,210.7,217.5,236.4,243.8,237.7,238.4,250.0,268.3
62,Amazônia Azul Tecnologias de Defesa S.A,TOTAL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,51.2,185.4,250.8,299.6,320.0,333.1,371.3
84,Fundo Naval,TOTAL,447.3,542.5,289.1,226.2,369.4,309.3,350.4,454.0,...,390.5,304.4,434.7,506.9,522.6,607.5,732.8,785.5,635.1,1277.4
7,Administração Direta,TOTAL,830.4,720.9,825.7,619.3,876.5,1595.5,1421.3,1609.3,...,1836.2,1224.8,1868.7,1908.6,2467.5,2119.8,2215.2,1475.1,2087.0,1824.1
80,Fundo do Exército,TOTAL,257.5,284.8,347.6,322.7,426.0,462.4,545.9,573.2,...,827.1,924.6,1042.7,1080.3,1121.0,1240.1,1103.4,1300.0,1730.9,2732.0
76,Fundo Aeronáutico,TOTAL,933.7,772.5,787.3,686.3,999.4,1003.9,1199.4,1256.8,...,1985.9,1817.8,1605.8,1969.1,2400.0,2202.3,2372.0,2804.1,3001.7,3103.9
14,Comando da Aeronáutica,TOTAL,4014.7,5787.1,6334.2,5783.3,6609.1,8189.4,8061.6,9554.9,...,12875.5,13686.4,14626.3,15793.0,17000.1,19264.6,19162.8,20624.3,22213.3,23554.0
28,Comando da Marinha,TOTAL,5064.2,6097.8,6760.0,6235.2,6402.3,7206.4,7887.7,8781.6,...,16037.6,16327.4,17455.2,19095.4,20228.0,20804.1,21062.2,24335.8,28934.3,33243.5
21,Comando do Exército,TOTAL,9072.8,11185.1,12728.4,11807.0,12697.1,14097.2,15920.1,17321.4,...,24973.3,26838.7,28730.0,29838.5,32283.2,34748.3,36849.6,40838.0,43333.5,45216.5
0,Total Ministério da Defesa,TOTAL,20696.4,25494.0,28176.2,25777.8,28513.2,33021.6,35581.1,39766.7,...,59452.3,61663.1,66378.8,70881.0,76874.2,81873.5,84508.9,93120.1,102938.3,111998.3